### ISSUE TITLE
North is in the wrong direction

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#319]
The client puts (0, 0) in the top left corner, and the North Direction is (0, 1). Seems unintuitive

**Comment by DSMan195276** [comment]
I would add that the [documentation](https://github.com/battlecode/battlecode-server/blob/master/src/main/battlecode/common/Direction.java#L63) disagrees with the current functionality - it says that `Direction.getNorth()` is a direction going 'up the screen', but it actually goes down the screen since it points away from the top-left corner.
